### ISSUE TITLE
Public-"ness" of your commits

### ISSUE THREAD

**Issue by akshitgaur2005** [Rahu1Goswami/Time-Machine-RNN#3]
This is to bring to your esteemed attention that every commit that you create on github is public and cannot be deleted.
So your pull request adding "kya be kutte :)" to my Time-Machine-RNN repo (through which this one is forked) is visible to all and can be seen by your teachers and potential recruiters.

All the best :)

**Comment by akshitgaur2005** [comment]
Also issues are for bringing bugs and sort to the attention of the maintainers.

**Comment by rahulgoswami121** [comment]
ah I see

**Comment by akshitgaur2005** [comment]
As the maintainer you can also close the issue!
